"""Inspection & Test Plan (ITP) PDF export — a physically-signable artifact
distinct from the JSON/HTML exports, for the commissioning authority to print
and hand off. Pure-Python (fpdf2, no Pango/Cairo system deps) so this doesn't
add a Docker/Render build risk.

Each case finding is resolved against the same commissioning-test catalog
(`data/corpus/commissioning/cx_plan.json`) `backend/agents/commissioning.py`
already uses — this reuses that data, it does not recompute or guess at test
definitions.
"""

from datetime import UTC, datetime

from fpdf import FPDF

from backend.agents.commissioning import _load_cx_plan

_SEVERITY_ORDER = {"Critical": 0, "Major": 1, "Minor": 2}

# fpdf2's core (non-embedded) fonts only support latin-1 - real finding text
# comes from user-pasted spec/submittal documents and can contain arbitrary
# Unicode (curly quotes, em-dashes, non-Latin scripts), which would otherwise
# hard-crash the export with FPDFUnicodeEncodingException. Transliterate the
# common cases, then drop anything still outside latin-1 rather than embed a
# full Unicode font (avoided to keep this a zero-extra-asset, pure-Python
# dependency, matching why fpdf2 was chosen over WeasyPrint in the first place).
_TRANSLITERATE = str.maketrans({
    "—": "-", "–": "-",  # em/en dash
    "‘": "'", "’": "'",  # curly single quotes
    "“": '"', "”": '"',  # curly double quotes
    "…": "...",               # ellipsis
})


def _safe(text) -> str:
    if text is None:
        return ""
    s = str(text).translate(_TRANSLITERATE)
    return s.encode("latin-1", errors="replace").decode("latin-1")


def _cx_lookup() -> dict[str, dict]:
    plan = _load_cx_plan()
    return {t["id"]: t for t in plan.get("tests", [])}


def _cx_authority() -> str:
    return _load_cx_plan().get("cx_authority", "Not specified")


def _finding_sort_key(finding: dict) -> tuple[int, str]:
    return _SEVERITY_ORDER.get(finding.get("severity"), 3), finding.get("component") or ""


def _new_itp_pdf(case: dict) -> FPDF:
    pdf = FPDF(orientation="L", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Inspection & Test Plan", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(90, 90, 90)
    generated = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    case_label = _safe(case.get("name") or case.get("case_id", ""))
    pdf.cell(
        0,
        6,
        f"Case: {case_label}  |  Generated: {generated}  |  Cx authority: {_safe(_cx_authority())}",
        new_x="LMARGIN",
        new_y="NEXT",
    )
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)
    return pdf


def _itp_row_values(index: int, finding: dict, test: dict) -> tuple[str, ...]:
    parameter = (finding.get("parameter") or "").replace("_", " ")
    unit = finding.get("unit") or ""
    deviation = _safe(
        f"{parameter}: required {finding.get('required_value')} {unit}, "
        f"submitted {finding.get('provided_value')} {unit}"
    )
    return (
        str(index),
        _safe(finding.get("component")),
        deviation,
        _safe(finding.get("severity")),
        _safe(finding.get("predicted_cx_test")) or "Unmapped",
        f"L{test.get('level')}" if test.get("level") else "",
        _safe(test.get("acceptance")),
        str(test.get("scheduled_week") or ""),
        "",
    )


def _render_itp_table(pdf: FPDF, ordered: list[dict], cx: dict[str, dict]) -> None:
    headers = ["#", "Component", "Deviation", "Sev.", "Cx Test", "Level", "Acceptance Criteria", "Wk", "Sign-off"]
    widths = [8, 32, 55, 14, 20, 30, 60, 12, 32]
    pdf.set_font("Helvetica", "B", 8)
    with pdf.table(col_widths=widths, text_align="LEFT", line_height=5) as table:
        row = table.row()
        for header in headers:
            row.cell(header)
        pdf.set_font("Helvetica", "", 7.5)
        for index, finding in enumerate(ordered, start=1):
            test = cx.get(finding.get("predicted_cx_test") or "", {})
            row = table.row()
            for value in _itp_row_values(index, finding, test):
                row.cell(value)


def _render_itp_disclaimer(pdf: FPDF) -> None:
    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(110, 110, 110)
    pdf.multi_cell(
        0,
        4,
        "Generated by Pramaan from the case's recorded findings and the project's "
        "commissioning-test catalog. This is a prototype-stage tool output, not a "
        "certified or field-validated inspection document - the commissioning "
        "authority named above is responsible for verifying every line against the "
        "governing standards before sign-off.",
    )


def build_itp_pdf(case: dict, findings: list[dict]) -> bytes:
    """Builds an Inspection & Test Plan PDF from a case's findings. Returns
    raw PDF bytes. Findings with no predicted_cx_test are still listed (with
    a blank test column) rather than silently dropped — an unmapped finding
    is still something a commissioning authority needs to see."""
    cx = _cx_lookup()
    ordered = sorted(findings, key=_finding_sort_key)

    pdf = _new_itp_pdf(case)

    if not ordered:
        pdf.set_font("Helvetica", "I", 11)
        pdf.cell(0, 8, "No findings recorded on this case yet.")
        return bytes(pdf.output())

    _render_itp_table(pdf, ordered, cx)

    _render_itp_disclaimer(pdf)
    return bytes(pdf.output())
